language: bash
sudo: true
services:
  - docker
before_install: 
  - docker pull mimosa/tengine
  - docker run -d -p 80:80 mimosa/tengine
  - docker ps -a
  - docker info
script:
  - curl -I http://localhost
