language: bash

sudo: true

install:
  - curl -sLo - https://raw.githubusercontent.com/moul/travis-docker/master/install.sh | sh -xe

script:
  - df -h
  - ./run docker info
  - ./run docker build -t="tengine" .
  - ./run docker info
  - df -h
